export const OFFERS_LIST_REQUEST="OFFERS_LIST_REQUEST";
export const OFFERS_LIST_SUCCESS="OFFERS_LIST_SUCCESS";
export const OFFERS_LIST_FAILURE="OFFERS_LIST_FAILURE";

export const OFFERS_DETAILS_REQUEST="OFFERS_DETAILS_REQUEST";
export const OFFERS_DETAILS_SUCCESS="OFFERS_DETAILS_SUCCESS";
export const OFFERS_DETAILS_FAILURE="OFFERS_DETAILS_FAILURE";

export const OPEN_OFFER_DETALS="OPEN_OFFER_DETALS";