export const CATEGORY_REQUEST="CATEGORY_REQUEST";
export const CATEGORY_SUCCESS="CATEGORY_SUCCESS";
export const CATEGORY_FAILURE="CATEGORY_FAILURE";

export const BANNER_REQUEST="BANNER_REQUEST";
export const BANNER_SUCCESS="BANNER_SUCCESS";
export const BANNER_FAILURE="BANNER_FAILURE";


